version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:latest

jobs:
  build-and-deploy:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            npm install
            npm run build

      - run:
          name: Deploy to GitHub Pages
          command: |
            curl -sSL https://github.com/actions/checkout/archive/v2.3.4.tar.gz | tar xz
            cd github-pages-deploy-action-4.1.1
            npm install
            node dist/index.js --branch gh-pages --folder dist/resume

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: master
