version: 2.1
orbs:
  nx: nrwl/nx@1.5.1
jobs:
  main:
    docker:
      - image: cimg/node:lts-browsers
    parallelism: 3
    steps:
      - checkout
      - run: npm ci
      - nx/set-shas

      - run: npx nx format:check
      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD -t lint --parallel=3
      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD -t test --parallel=3 --configuration=ci
      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD -t build --parallel=3
  deploy-to-github-pages:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build
          command: npm run build

      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "paulortesjr@gmail.com"
            git config --global user.name "Paulo Tessarolli"
            git clone --branch gh-pages --depth 1 --no-checkout git@github.com:paulortesjr/resume.git ./deploy-gh-pages
            mv ./dist/resume/* ./deploy-gh-pages/
            cd ./deploy-gh-pages
            git add .
            git commit -m "Deploying to GitHub Pages"
            git push origin gh-pages
workflows:
  build:
    jobs:
      - main
  deploy:
    jobs:
      - build
      - deploy-to-github-pages:
          requires:
            - build-and-test
