name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to the name of your main branch
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          npm run build --baseHref=/resume/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # Change this to the name of your publishing branch
          folder: dist/resume
